version: 2.0
jobs:
  test:
    docker:
      - image: circleci/python:3
    steps: 
      - checkout
      - run: 
          command: |
            pip install -r requirements.txt 
            python tests.py
workflows: 
  version: 2
  test: 
    jobs: 
      - test
